// Multi-language support for ADDIT

export const LANGS = {
  en: {
    appName: 'ADDIT',
    appTagline: 'Your Smart Shopping Budget',
    // PIN Screen
    enterPin: 'Enter your PIN',
    createPin: 'Create a 6-digit PIN',
    confirmPin: 'Confirm your PIN',
    pinMismatch: 'PINs do not match',
    wrongPin: 'Wrong PIN',
    // Home Screen
    myList: 'My List',
    addItem: 'Add Item',
    scanBarcode: 'Scan Barcode',
    scanLabel: 'Scan Price Label',
    total: 'Total',
    remaining: 'Remaining',
    overBudget: 'Over budget!',
    emptyList: 'Your list is empty',
    itemName: 'Item name',
    price: 'Price',
    quantity: 'Qty',
    delete: 'Delete',
    clearAll: 'Clear All',
    saveSession: 'Save Session',
    sessionSaved: 'Session saved!',
    // Calculator
    calculator: 'Calculator',
    addToList: 'Add to List',
    result: 'Result',
    // History
    history: 'History',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    noHistory: 'No shopping history',
    items: 'items',
    // Settings
    settings: 'Settings',
    budget: 'Budget',
    language: 'Language',
    currency: 'Currency',
    setBudget: 'Set Budget',
    resetPin: 'Reset PIN',
    about: 'About',
    version: 'Version',
    // Scanner
    scannerMode: 'Scanner Mode',
    labelMode: 'Price Label',
    barcodeMode: 'Barcode',
    scanPrice: 'Scan Price',
    close: 'Close',
    scanning: 'Scanning...',
    productNotFound: 'Product not found',
    // Common
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    edit: 'Edit',
    done: 'Done',
  },
  fr: {
    appName: 'ADDIT',
    appTagline: 'Votre budget courses intelligent',
    // PIN Screen
    enterPin: 'Entrez votre code PIN',
    createPin: 'Créez un code PIN à 6 chiffres',
    confirmPin: 'Confirmez votre code PIN',
    pinMismatch: 'Les codes PIN ne correspondent pas',
    wrongPin: 'Code PIN incorrect',
    // Home Screen
    myList: 'Ma Liste',
    addItem: 'Ajouter un article',
    scanBarcode: 'Scanner un code-barres',
    scanLabel: 'Scanner une étiquette prix',
    total: 'Total',
    remaining: 'Restant',
    overBudget: 'Budget dépassé !',
    emptyList: 'Votre liste est vide',
    itemName: 'Nom de l\'article',
    price: 'Prix',
    quantity: 'Qté',
    delete: 'Supprimer',
    clearAll: 'Tout effacer',
    saveSession: 'Sauvegarder',
    sessionSaved: 'Session sauvegardée !',
    // Calculator
    calculator: 'Calculatrice',
    addToList: 'Ajouter à la liste',
    result: 'Résultat',
    // History
    history: 'Historique',
    today: 'Aujourd\'hui',
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois',
    thisYear: 'Cette année',
    noHistory: 'Aucun historique',
    items: 'articles',
    // Settings
    settings: 'Paramètres',
    budget: 'Budget',
    language: 'Langue',
    currency: 'Devise',
    setBudget: 'Définir le budget',
    resetPin: 'Réinitialiser le PIN',
    about: 'À propos',
    version: 'Version',
    // Scanner
    scannerMode: 'Mode Scanner',
    labelMode: 'Étiquette Prix',
    barcodeMode: 'Code-barres',
    scanPrice: 'Scanner le prix',
    close: 'Fermer',
    scanning: 'Scan en cours...',
    productNotFound: 'Produit non trouvé',
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    edit: 'Modifier',
    done: 'Terminé',
  },
  de: {
    appName: 'ADDIT',
    appTagline: 'Ihr intelligentes Einkaufsbudget',
    enterPin: 'PIN eingeben',
    createPin: '6-stellige PIN erstellen',
    confirmPin: 'PIN bestätigen',
    pinMismatch: 'PINs stimmen nicht überein',
    wrongPin: 'Falsche PIN',
    myList: 'Meine Liste',
    addItem: 'Artikel hinzufügen',
    scanBarcode: 'Barcode scannen',
    scanLabel: 'Preisschild scannen',
    total: 'Gesamt',
    remaining: 'Übrig',
    overBudget: 'Budget überschritten!',
    emptyList: 'Ihre Liste ist leer',
    itemName: 'Artikelname',
    price: 'Preis',
    quantity: 'Anz.',
    delete: 'Löschen',
    clearAll: 'Alles löschen',
    saveSession: 'Speichern',
    sessionSaved: 'Sitzung gespeichert!',
    calculator: 'Rechner',
    addToList: 'Zur Liste hinzufügen',
    result: 'Ergebnis',
    history: 'Verlauf',
    today: 'Heute',
    thisWeek: 'Diese Woche',
    thisMonth: 'Dieser Monat',
    thisYear: 'Dieses Jahr',
    noHistory: 'Kein Verlauf',
    items: 'Artikel',
    settings: 'Einstellungen',
    budget: 'Budget',
    language: 'Sprache',
    currency: 'Währung',
    setBudget: 'Budget festlegen',
    resetPin: 'PIN zurücksetzen',
    about: 'Über',
    version: 'Version',
    scannerMode: 'Scanner-Modus',
    labelMode: 'Preisschild',
    barcodeMode: 'Barcode',
    scanPrice: 'Preis scannen',
    close: 'Schließen',
    scanning: 'Scannen...',
    productNotFound: 'Produkt nicht gefunden',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    edit: 'Bearbeiten',
    done: 'Fertig',
  },
  es: {
    appName: 'ADDIT',
    appTagline: 'Tu presupuesto de compras inteligente',
    enterPin: 'Introduce tu PIN',
    createPin: 'Crea un PIN de 6 dígitos',
    confirmPin: 'Confirma tu PIN',
    pinMismatch: 'Los PIN no coinciden',
    wrongPin: 'PIN incorrecto',
    myList: 'Mi Lista',
    addItem: 'Añadir artículo',
    scanBarcode: 'Escanear código de barras',
    scanLabel: 'Escanear etiqueta de precio',
    total: 'Total',
    remaining: 'Restante',
    overBudget: '¡Presupuesto excedido!',
    emptyList: 'Tu lista está vacía',
    itemName: 'Nombre del artículo',
    price: 'Precio',
    quantity: 'Cant.',
    delete: 'Eliminar',
    clearAll: 'Limpiar todo',
    saveSession: 'Guardar',
    sessionSaved: '¡Sesión guardada!',
    calculator: 'Calculadora',
    addToList: 'Añadir a la lista',
    result: 'Resultado',
    history: 'Historial',
    today: 'Hoy',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mes',
    thisYear: 'Este año',
    noHistory: 'Sin historial',
    items: 'artículos',
    settings: 'Configuración',
    budget: 'Presupuesto',
    language: 'Idioma',
    currency: 'Moneda',
    setBudget: 'Establecer presupuesto',
    resetPin: 'Restablecer PIN',
    about: 'Acerca de',
    version: 'Versión',
    scannerMode: 'Modo Escáner',
    labelMode: 'Etiqueta de Precio',
    barcodeMode: 'Código de barras',
    scanPrice: 'Escanear precio',
    close: 'Cerrar',
    scanning: 'Escaneando...',
    productNotFound: 'Producto no encontrado',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    edit: 'Editar',
    done: 'Hecho',
  },
  pt: {
    appName: 'ADDIT',
    appTagline: 'Seu orçamento de compras inteligente',
    enterPin: 'Digite seu PIN',
    createPin: 'Crie um PIN de 6 dígitos',
    confirmPin: 'Confirme seu PIN',
    pinMismatch: 'PINs não correspondem',
    wrongPin: 'PIN incorreto',
    myList: 'Minha Lista',
    addItem: 'Adicionar item',
    scanBarcode: 'Escanear código de barras',
    scanLabel: 'Escanear etiqueta de preço',
    total: 'Total',
    remaining: 'Restante',
    overBudget: 'Orçamento excedido!',
    emptyList: 'Sua lista está vazia',
    itemName: 'Nome do item',
    price: 'Preço',
    quantity: 'Qtd.',
    delete: 'Excluir',
    clearAll: 'Limpar tudo',
    saveSession: 'Salvar',
    sessionSaved: 'Sessão salva!',
    calculator: 'Calculadora',
    addToList: 'Adicionar à lista',
    result: 'Resultado',
    history: 'Histórico',
    today: 'Hoje',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mês',
    thisYear: 'Este ano',
    noHistory: 'Sem histórico',
    items: 'itens',
    settings: 'Configurações',
    budget: 'Orçamento',
    language: 'Idioma',
    currency: 'Moeda',
    setBudget: 'Definir orçamento',
    resetPin: 'Redefinir PIN',
    about: 'Sobre',
    version: 'Versão',
    scannerMode: 'Modo Scanner',
    labelMode: 'Etiqueta de Preço',
    barcodeMode: 'Código de barras',
    scanPrice: 'Escanear preço',
    close: 'Fechar',
    scanning: 'Escaneando...',
    productNotFound: 'Produto não encontrado',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    edit: 'Editar',
    done: 'Concluído',
  },
  ja: {
    appName: 'ADDIT',
    appTagline: 'スマートショッピング予算',
    enterPin: 'PINを入力',
    createPin: '6桁のPINを作成',
    confirmPin: 'PINを確認',
    pinMismatch: 'PINが一致しません',
    wrongPin: '間違ったPIN',
    myList: 'リスト',
    addItem: 'アイテムを追加',
    scanBarcode: 'バーコードをスキャン',
    scanLabel: '価格ラベルをスキャン',
    total: '合計',
    remaining: '残り',
    overBudget: '予算超過！',
    emptyList: 'リストが空です',
    itemName: 'アイテム名',
    price: '価格',
    quantity: '数量',
    delete: '削除',
    clearAll: 'すべてクリア',
    saveSession: '保存',
    sessionSaved: 'セッション保存完了！',
    calculator: '電卓',
    addToList: 'リストに追加',
    result: '結果',
    history: '履歴',
    today: '今日',
    thisWeek: '今週',
    thisMonth: '今月',
    thisYear: '今年',
    noHistory: '履歴なし',
    items: 'アイテム',
    settings: '設定',
    budget: '予算',
    language: '言語',
    currency: '通貨',
    setBudget: '予算を設定',
    resetPin: 'PINをリセット',
    about: 'について',
    version: 'バージョン',
    scannerMode: 'スキャナーモード',
    labelMode: '価格ラベル',
    barcodeMode: 'バーコード',
    scanPrice: '価格をスキャン',
    close: '閉じる',
    scanning: 'スキャン中...',
    productNotFound: '製品が見つかりません',
    save: '保存',
    cancel: 'キャンセル',
    confirm: '確認',
    edit: '編集',
    done: '完了',
  },
  ko: {
    appName: 'ADDIT',
    appTagline: '스마트 쇼핑 예산',
    enterPin: 'PIN 입력',
    createPin: '6자리 PIN 생성',
    confirmPin: 'PIN 확인',
    pinMismatch: 'PIN이 일치하지 않습니다',
    wrongPin: '잘못된 PIN',
    myList: '내 목록',
    addItem: '항목 추가',
    scanBarcode: '바코드 스캔',
    scanLabel: '가격표 스캔',
    total: '총계',
    remaining: '남은 금액',
    overBudget: '예산 초과!',
    emptyList: '목록이 비어있습니다',
    itemName: '항목 이름',
    price: '가격',
    quantity: '수량',
    delete: '삭제',
    clearAll: '모두 지우기',
    saveSession: '저장',
    sessionSaved: '세션 저장됨!',
    calculator: '계산기',
    addToList: '목록에 추가',
    result: '결과',
    history: '기록',
    today: '오늘',
    thisWeek: '이번 주',
    thisMonth: '이번 달',
    thisYear: '올해',
    noHistory: '기록 없음',
    items: '항목',
    settings: '설정',
    budget: '예산',
    language: '언어',
    currency: '통화',
    setBudget: '예산 설정',
    resetPin: 'PIN 재설정',
    about: '정보',
    version: '버전',
    scannerMode: '스캐너 모드',
    labelMode: '가격표',
    barcodeMode: '바코드',
    scanPrice: '가격 스캔',
    close: '닫기',
    scanning: '스캔 중...',
    productNotFound: '제품을 찾을 수 없습니다',
    save: '저장',
    cancel: '취소',
    confirm: '확인',
    edit: '편집',
    done: '완료',
  },
  zh: {
    appName: 'ADDIT',
    appTagline: '智能购物预算',
    enterPin: '输入PIN码',
    createPin: '创建6位PIN码',
    confirmPin: '确认PIN码',
    pinMismatch: 'PIN码不匹配',
    wrongPin: 'PIN码错误',
    myList: '我的清单',
    addItem: '添加项目',
    scanBarcode: '扫描条形码',
    scanLabel: '扫描价格标签',
    total: '总计',
    remaining: '剩余',
    overBudget: '超出预算！',
    emptyList: '清单为空',
    itemName: '项目名称',
    price: '价格',
    quantity: '数量',
    delete: '删除',
    clearAll: '清除所有',
    saveSession: '保存',
    sessionSaved: '会话已保存！',
    calculator: '计算器',
    addToList: '添加到清单',
    result: '结果',
    history: '历史记录',
    today: '今天',
    thisWeek: '本周',
    thisMonth: '本月',
    thisYear: '今年',
    noHistory: '无历史记录',
    items: '项目',
    settings: '设置',
    budget: '预算',
    language: '语言',
    currency: '货币',
    setBudget: '设置预算',
    resetPin: '重置PIN码',
    about: '关于',
    version: '版本',
    scannerMode: '扫描模式',
    labelMode: '价格标签',
    barcodeMode: '条形码',
    scanPrice: '扫描价格',
    close: '关闭',
    scanning: '扫描中...',
    productNotFound: '未找到产品',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    edit: '编辑',
    done: '完成',
  },
} as const;

export type LangCode = keyof typeof LANGS;

export const LANGUAGE_NAMES: Record<LangCode, string> = {
  en: 'English',
  fr: 'Français',
  de: 'Deutsch',
  es: 'Español',
  pt: 'Português',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
};

export const useLang = (code: LangCode) => LANGS[code] ?? LANGS.en;
